AndrewIngram/django-extra-views

extra_views/generic.py
extra_views/tests/models.py
extra_views/tests/tests.py

Hello @AndrewIngram,
I just made some changes to make `django-extra-views` compatible with Django 1.9. Most of them were in test modules, but it was still required so I took some time to fix everything. :)
Please note that all my changes work the same way, they check the current version of Django. Also, the new modules are used even with Django 1.8, since those modules already exist in this version (and it removes the warnings as well).
Feel free to comment or ask for any modification.
PS: I checked that the test suite still work with:
- Python 2.7 and Django 1.4.0
- Python 3.4 and Django 1.4.0
- Python 3.4 and Django 1.8.2
(and I let Travis to check the rest)

Fix all RemovedInDjango19Warning messages. Fixes #101

---

.travis.yml
tox.ini

Hello,
I am suggest add tests over django master to fast feedback what can be broken in future django releases. It is failurable tests, so provide feedback, but isn't misleading for developer which create a pull requests. It doesn't affect GitHub pull requests status.
Greetings,

Add tests over django-master

---

extra_views/advanced.py
extra_views_tests/tests.py
extra_views_tests/urls.py

The parent mixins/classes don't take `*args`, so we extra-views shouldn't pass them either.
Added a test that fails before the patch.

Fixes #122: don't pass *args to get_context_data

---

.travis.yml

The 1.6 build is failing without reason.
Django 1.6 is not supported since April 1st, 2015

Remove Django 1.6 support

---

extra_views/contrib/mixins.py
extra_views_tests/tests.py

Traceback (most recent call last):
File "/home/ubuntu/env_prod/lib/python3.6/site-packages/django/core/handlers/exception.py", line 42, in inner
response = get_response(request)
File "/home/ubuntu/env_prod/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
response = self._get_response(request)
File "/home/ubuntu/env_prod/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/home/ubuntu/env_prod/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/ubuntu/env_prod/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in …

TypeError: reduce() of empty sequence with no initial value

---

extra_views/formsets.py

When using forms rendered as modals on a larger page, it is convenient
to use form prefixes passed by GET parameter.
Using the `get_prefix` method then allows us to return and handle the
prefix correctly:
```python
class PrefixedFormMixin(generic.edit.FormMixin):
def get_prefix(self):
return self.request.GET.get('prefix', self.prefix)
```
Ref:
http://ccbv.co.uk/projects/Django/1.11/django.views.generic.edit/FormMixin/#get_prefix

Handle prefix as generic.FormMixin does

---

extra_views/formsets.py

Quote from the 1.11 release notes[1]
```
For consistency with non-multipart requests,
MultiPartParser.parse() now leaves request.POST immutable.
If you’re modifying that QueryDict, you must now first copy it, e.g. request.POST.copy().
```
This is relevant in https://github.com/AndrewIngram/django-extra-views/blob/master/extra_views/formsets.py#L76. I tried running the automated tests with django1.11, but they passed. Changing `request.POST` to `request.POST.copy()` fixes my test failure.
[1] https://docs.djangoproject.com/en/2.0/releases/1.11/

[Django1.11] AttributeError: This QueryDict instance is immutable

---

.travis.yml
CHANGELOG.rst
docs/views.rst
extra_views/formsets.py
extra_views/generic.py
extra_views_tests/forms.py
extra_views_tests/tests.py
extra_views_tests/urls.py
extra_views_tests/views.py
tox.ini

An up to date pull request for #115. Also addresses #123. A few notes on what I've done here:
- Wherever possible. attempted to imitate functionality from `FormView`. That means calling `get_initial` and `get_prefix` to get class level attributes, but leaving all other kwargs to be set in either `formset_kwargs` or `factory_kwargs`.  `exclude` and `fields` have been left at the class level for analogous reasons.
- When setting mutable attributes at the class level, returning a copy of them to prevent them being modified.
- `can_delete` is set to the default value automatically by the respective formset_factory of the class, so there is no need for us to set it by default.
I was hoping to remove `get_extra_form_kwargs` completely but we need to wait until support is dropped for django 1.8.

Formset kwargs (New)

---

.travis.yml
CHANGELOG.rst
extra_views/generic.py
setup.py
tox.ini

This is the first time I've done one of these so if there's anything obvious I've missed, let me know. I've left the actual release number and date unchanged...

Removed support for Django 1.7 and 1.8

---

extra_views_tests/views.py
tox.ini

Looks like Django 2.0 is more strict about using trailing slashes...and I added Django 1.11 back into the tox test environment for Python 3.

Fix for Django 2.0 tests

---

extra_views/formsets.py
extra_views/generic.py

1. Moved BaseFormSetMixin.success_url to FormSetMixin.success_url, as this specifically relates to functionality of a subclassed view.
2. Removed ModelFormSetMixin.get_context_data() method as django now uses self.object_list correctly (rather than requiring it to be in **kwargs which was previously the case).
3. ModelFormSetMixin.get_factory_kwargs and InlineFormSetMixin.get_factory_kwargs were both calling self().get_formset_class() a second time even though this would already have been called by BaseFormSetMixin.factory_kwargs() as part of the super() call. The extra calls have been removed.
4. Removed explicit setting of BaseInlineFormSetMixin.formset_class and GenericInlineFormSetMixin.formset_class as the defaults for inlineformset_factory and genericinlineformset_factory set this …

Simple clean up changes.

---

CHANGELOG.rst
README.rst
docs/misc.rst
docs/views.rst
extra_views/__init__.py
extra_views/advanced.py
extra_views/formsets.py
extra_views/generic.py
extra_views_tests/views.py

Let me know if the way I've handled the deprecation warnings is OK; I assumed just checking on ``__init__`` would be sufficient.
#165.

Renamed InlineFormSet to InlineFormSetFactory and other renames

---

extra_views_tests/models.py
extra_views_tests/tests.py
extra_views_tests/views.py

As per #92. This happens automatically because our `ModelFormWithInlinesMixin` inherits from Django's `ModelFormMixin` which correctly uses `get_absolute_url()` for the success_url.

Test that get_absolute_url() is used in success_url of Create/UpdateWithInlinesView

---

CHANGELOG.rst
docs/pages/formset-customization.rst
extra_views/__init__.py
extra_views/advanced.py
extra_views_tests/tests.py
extra_views_tests/views.py
runtests.py

This replaces PR #147 and uses most of what @freeworlder did. I have added documentation and updated the tests.
One change I made was to add `inlines` to the arguments of `SuccessMessageMixin.get_success_message()` so that they can be used in the success message. This seemed in line with what was discussed in #59.
Apologies that the commit history is a little messy, am happy to clean it up if requested.

Complete Messages Mixin

---

docs/pages/formset-customization.rst

Correcting typos in example code for `get_formset_kwargs` documentation

---

CHANGELOG.rst
extra_views/advanced.py
extra_views_tests/tests.py

As per issue #155.
@Murfen please confirm if this resolves the issue for you.

Revert view.object back to original value if inline validation fails

---

tox.ini

Missing comma, which meant that upper bound was ignored (so these were actually running with 2.2).

Fix typo in tox django version spec

---

setup.py

Some tools pull a Python modules license from the classifiers list. This PR adds a line for that.

Add license to trove classifiers.

---

docs/pages/formset-views.rst

There is a small typo in docs/pages/formset-views.rst.
Should read `available` rather than `availble`.

docs: Fix simple typo, availble -> available

---

docs/pages/formset-views.rst

in a dictionary  `, ` was typed instead of `:`

fixed a typo

---

.travis.yml
extra_views_tests/tests.py
extra_views_tests/urls.py
tox.ini

The management form test was broken, as Django >= 3.2 uses a formset error rather than raising an exception.
Also fixed extra_views_tests to use django.urls.path in preparation for Django 4.0, and removed Python 3.6 and 3.7 from djangomaster as Django >= 4.0 does not support them.
There's no rush to release as these are updates to the test suite and not the actual module.

Fix tests for Django 3.2 and djangomaster

---

extra_views/advanced.py

When using `get_inlines` and `get_inlines_names`, a new copy of the object is returned, avoiding changing the class attribute.

Behavior of immutable attributes

---

docs/conf.py

This occurred because we don't use specific version of black (or isort / flake8). Should we?

Reformat docs/conf.py for latest version of black.

---

setup.py

setting the keyword argument python_requires is a better way to declare Python compatibility #253

add requires_python

---

.github/workflows/tests.yml
CHANGELOG.rst
tox.ini

Bumped test suite. Is it time to remove testing for 3.0 and 3.1 now?
https://endoflife.date/django

Added support for Python 3.12, Django 5.0.

---

.github/workflows/tests.yml
CHANGELOG.rst
docs/pages/formset-customization.rst
docs/pages/formset-views.rst
extra_views/formsets.py
extra_views_tests/tests.py
extra_views_tests/views.py

Replacement PR for #257 to address #256.
To add class attribute and method to make overriding `form_kwargs` more convenient.

Added BaseFormSetFactory.form_kwargs and .get_form_kwargs().

---

.github/workflows/tests.yml
CHANGELOG.rst
extra_views_tests/tests.py
tox.ini

I am not sure what changed in Django 5.2, but I was getting this error while running tests:
```
[   20s] =================================== FAILURES ===================================
[   20s] _________________________ FormSetViewTests.test_create _________________________
[   20s] 
[   20s] self = <extra_views_tests.tests.FormSetViewTests testMethod=test_create>
[   20s] 
[   20s]     def test_create(self):
[   20s]         res = self.client.get("/formset/simple/")
[   20s]         self.assertEqual(res.status_code, 200)
[   20s]         self.assertTrue("formset" in res.context_data)
[   20s]         self.assertFalse("form" in res.context_data)
[   20s]         self.assertTemplateUsed(res, "extra_views/address_formset.html")
[   20s] >       self.assertEqual(
[   20s] …
```

make tests compatible with Django 5.2
